// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPzKqr1nlOi-Gy2b44YZHNg70zzbFE46E',
    appId: '1:293647419834:web:15d0a60bc0de299494b583',
    messagingSenderId: '293647419834',
    projectId: 'selada-d6ade',
    authDomain: 'selada-d6ade.firebaseapp.com',
    databaseURL: 'https://selada-d6ade-default-rtdb.firebaseio.com',
    storageBucket: 'selada-d6ade.firebasestorage.app',
    measurementId: 'G-Z594Q19NBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdsbo_MrANbonvVEG54tT5qSDOnVnwzeg',
    appId: '1:293647419834:android:3702be016dd7d01594b583',
    messagingSenderId: '293647419834',
    projectId: 'selada-d6ade',
    databaseURL: 'https://selada-d6ade-default-rtdb.firebaseio.com',
    storageBucket: 'selada-d6ade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt7WgdlxRgHC9DIy84_e1JaQHmF2Y_uO4',
    appId: '1:293647419834:ios:fb7a762caebffac294b583',
    messagingSenderId: '293647419834',
    projectId: 'selada-d6ade',
    databaseURL: 'https://selada-d6ade-default-rtdb.firebaseio.com',
    storageBucket: 'selada-d6ade.firebasestorage.app',
    iosBundleId: 'com.example.proyekakhir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt7WgdlxRgHC9DIy84_e1JaQHmF2Y_uO4',
    appId: '1:293647419834:ios:fb7a762caebffac294b583',
    messagingSenderId: '293647419834',
    projectId: 'selada-d6ade',
    databaseURL: 'https://selada-d6ade-default-rtdb.firebaseio.com',
    storageBucket: 'selada-d6ade.firebasestorage.app',
    iosBundleId: 'com.example.proyekakhir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPzKqr1nlOi-Gy2b44YZHNg70zzbFE46E',
    appId: '1:293647419834:web:297bbbad975d78a394b583',
    messagingSenderId: '293647419834',
    projectId: 'selada-d6ade',
    authDomain: 'selada-d6ade.firebaseapp.com',
    databaseURL: 'https://selada-d6ade-default-rtdb.firebaseio.com',
    storageBucket: 'selada-d6ade.firebasestorage.app',
    measurementId: 'G-KTDR9J76ZL',
  );

}